spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.44.128:3306/finance?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  resources:
    static-locations: classpath:/

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

background:
  errorLog: true
  swagger:
    defaultToken: 21748DDA7AE4F5A70A213A916ADFBA34